Algoritmo "semnome"
Var
nome: caracter
cod: inteiro
val, valt ,porcent: real
Inicio
escreval ("Digite seu nome:")
leia (nome)
escreval ( " ")
escreval (" ")
escreval ("digite o código")
leia (cod)
escreval (" ")
escreval ("valor do produto")
leia (val)
escreval (" ")
escreval ("digite a porcentagem de desconto")
leia (porcent)
valt<- (val-val*porcent/100)
escreval (" ")
escreval ("valor total será de",valt)




Fimalgoritmo