Algoritmo "semnome"
//media de 3 notas
Var
// Seção de Declarações das variáveis
nota1, nota2, nota3:real
media:real
nota:real
soma : real


Inicio
escreval ("digite a primeira nota: ")
leia (nota1)
escreval (" digite a segunda nota: " )
leia (nota2)
escreval ( "digite a terceira nota: ")
leia (nota3)
soma<- nota1+nota2+nota3
media<- soma/3
escreval ("sua média é : ", media)



Fimalgoritmo