Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/12/2022
Var
// Seção de Declarações das variáveis 
idade: vetor [0..5] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval (" digite um valor para a posiçao 3")
leia (idade[3])

idade [2] <- 15
escreval (" o valor da posiçao 3 eh : ", idade [3])




Fimalgoritmo