Algoritmo "semnome"
// valor unitario do lanche
Var
// Seção de Declarações das variáveis 
valoruni:real
quantidade:inteiro
lanche:caracter
 soma:real
Inicio

escreval (" O valor unitário do lanche é R$ 4,50")
escreval ("digite o valor unitario!")
leia (valoruni)
escreval ("quantos lanches voce deseja?")
leia (quantidade)


soma<-valoruni*quantidade
escreval (" O valor a ser pago é:R$",soma)

Fimalgoritmo